FROM node:22.8.0-slim

ARG NODEMON_VERSION=3.1.7

RUN apt update && \
    apt install -y curl && \
    npm install -g nodemon@${NODEMON_VERSION}

COPY start.sh /
RUN chmod +x /start.sh

# RUN useradd -m -u 1000 node

USER node
RUN mkdir /home/node/app
WORKDIR /home/node/app

# COPY package.json ./
# RUN npm install

EXPOSE 3000

# CMD [ "tail", "-f", "/dev/null" ]
# CMD [ "sh", "-c", "npm install && tail -f /dev/null" ]


CMD [ "/start.sh" ]